site_name: Webhook Manager
site_url: https://github.com/versx/WhMgr
site_description: Webhook manager
site_author: versx

repo_url: https://github.com/versx/whmgr/
edit_uri: ""

theme:
    name: flatly #mkdocs, bootstrap4, cinder, cosmo, cyborg, flatly, ivory, material, readthedocs, slate, yeti

extends: mkdocs
hljs_style: docco

nav:
    - Home: index.md
    - General:
        - Screenshots: screenshots.md
        - Terminology: terminology.md
        - Updating: updating.md
    - User Guide:
        - Getting Started: user-guide/getting-started.md
        - Config: user-guide/config.md
            - Discord: user-guide/discords.md
        - Geofences: user-guide/geofences.md
        - Alarms: user-guide/alarms.md
        - Filters: user-guide/filters.md
        - Alerts: user-guide/alerts.md
        - DTS:
            - Pokemon: user-guide/dts/pokemon.md
            - Raids & Eggs: user-guide/dts/raids.md
            - Quests: user-guide/dts/quests.md
            - Pokestops: user-guide/dts/pokestops.md
            - Gyms: user-guide/dts/gyms.md
            - Weather: user-guide/dts/weather.md
            - Nests: user-guide/dts/nests.md
    - Commands:
        - Subscriptions: commands/subscriptions.md
        - Owner: commands/owner.md
    - Other:
        - Command Line: other/commandline.md
#    - About:
#        - Release Notes: about/release-notes.md
#        - Contributing: about/contributing.md

markdown_extensions:
    - toc:
        permalink: ÔÉÅ

copyright: Copyright &copy; 2019 <a href="https://github.com/versx">versx</a>, Maintained by <a href="/about/release-notes.md#maintenance-team">versx</a>.

plugins:
    - search

extra_css:
    - css/base.css
    - css/bootstrap-custom.min.css