site_name: Webhook Manager
site_url: https://github.com/versx/WhMgr
site_description: Webhook Manager
site_author: versx

repo_url: https://github.com/versx/whmgr/
edit_uri: ""

theme:
    name: readthedocs #mkdocs, bootstrap4, cinder, cosmo, cyborg, flatly, ivory, material, readthedocs, slate, yeti

plugins:
    - search:
        separator: '[\s\-\.]+'
        lang: en

nav:
    - General:
        - Home: index.md
        - Screenshots: screenshots.md
        - Terminology: terminology.md
    - Installation:
        - Prerequisites: install/prerequisites.md
        - Getting Started: install/getting-started.md
        - Updating: install/updating.md
    - Configuration:
        - Config: config/config.md
        - Discord: config/discords.md
        - Geofences: config/geofences.md
        - Alarms: config/alarms.md
        - Filters: config/filters.md
        - Embeds: config/embeds.md
    - DTS:
        - Pokemon: dts/pokemon.md
        - Raids & Eggs: dts/raids.md
        - Quests: dts/quests.md
        - Pokestops: dts/pokestops.md
        - Gyms: dts/gyms.md
        - Weather: dts/weather.md
        - Nests: dts/nests.md
    - Commands:
        - Subscriptions: commands/subscriptions.md
        - Owner: commands/owner.md
    - Other:
        - Command Line: other/commandline.md
        - Geocoding: other/geocoding.md
        - PM2: other/pm2.md
#    - About:
#        - Release Notes: about/release-notes.md
#        - Contributing: about/contributing.md

markdown_extensions:
    - toc:
        permalink: ÔÉÅ

copyright: Copyright &copy; 2021, Maintained by <a href="https://github.com/versx">versx</a>.

extra_css:
    - css/base.css
    - css/bootstrap-custom.min.css
